In [2]:
import pandas as pd

In [3]:
X = pd.read_csv('housing_X.csv')
y = pd.read_csv('housing_y.csv')

# to_csv -> Index=False

In [4]:
X = X.drop(columns='Unnamed: 0')
y = y.drop(columns='Unnamed: 0')

In [5]:
# split to train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [6]:
# kalau tidak melakukan scaling langsung saja ke lasso regression
from sklearn.linear_model import Lasso

ls = Lasso()

ls.fit(X_train, y_train) # kalau ingin mengubah menggunakan transform, kalau ingin prediksi maka gunakan predict

Lasso()

In [7]:
ls.predict(X_test)
ls.coef_

array([-0.07660927,  0.02850064, -0.        ,  0.        , -0.        ,
        1.63048892,  0.01639478, -0.63085765,  0.21965363, -0.01228558,
       -0.70858233,  0.0111811 , -0.74710661])

In [8]:
# melihat visualisasinya
pd.DataFrame(
    {
        'column': X.columns,
        'importance': ls.coef_
    }
)

     column  importance
0      CRIM   -0.076609
1        ZN    0.028501
2     INDUS   -0.000000
3      CHAS    0.000000
4       NOX   -0.000000
5        RM    1.630489
6       AGE    0.016395
7       DIS   -0.630858
8       RAD    0.219654
9       TAX   -0.012286
10  PTRATIO   -0.708582
11        B    0.011181
12    LSTAT   -0.747107

In [9]:
X.corr() # melihat korelasi antar columnnya, melihat korelasi antara feature sangat penting karena seharusnya feature hanya memiliki korelasi yang kuat ke target

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993
PTRATIO,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000

In [10]:
import joblib

best_rfc = joblib.load('best_model_rfc.joblib')

d:\DEVELOPMENTS\BELAJAR\dsml\.venv\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.9.1 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
d:\DEVELOPMENTS\BELAJAR\dsml\.venv\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.9.1 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [11]:
best_rfc.feature_importances_ # Feature penting dari nilai impurity (nilai split, baseon)

array([0.14690873, 0.26739463, 0.09692774, 0.02478659, 0.37694851,
       0.07927448, 0.00775932])

In [12]:
pd.read_csv('adult_X.csv')

,Unnamed: 0,workclass,age,education-num,marital-status,occupation,hours-per-week,native-country
0,0,State-gov,39,13,Never-married,Adm-clerical,40,United-States
1,1,Self-emp-not-inc,50,13,Married-civ-spouse,Exec-managerial,13,United-States
2,2,Private,38,9,Divorced,Handlers-cleaners,40,United-States
3,3,Private,53,7,Married-civ-spouse,Handlers-cleaners,40,United-States
4,4,Private,28,13,Married-civ-spouse,Prof-specialty,40,Cuba
...,...,...,...,...,...,...,...,...
47980,48837,Private,39,13,Divorced,Prof-specialty,36,United-States
47981,48838,Never-worked,64,9,Widowed,Never-worked,40,United-States
47982,48839,Private,38,13,Married-civ-spouse,Prof-specialty,50,United-States
47983,48840,Private,44,13,Divorced,Adm-clerical,40,United-States
47984,48841,Self-emp-inc,35,13,Married-civ-spouse,Exec-managerial,60,United-States

## Deployment
### 1. Pipeline
membungkus proses awal sampai akhir sehingga nanti bisa digunakan untuk ekpsrimen selanjutnyya

In [13]:

X = pd.read_csv('adult_X.csv').drop(columns='Unnamed: 0')
y = pd.read_csv('adult_y.csv').drop(columns='Unnamed: 0')

In [14]:
X.columns

Index(['workclass', 'age', 'education-num', 'marital-status', 'occupation',
       'hours-per-week', 'native-country'],
      dtype='object')

In [15]:
X.dtypes

workclass         object
age                int64
education-num      int64
marital-status    object
occupation        object
hours-per-week     int64
native-country    object
dtype: object

In [16]:
# Pilih column sesuai type column

numeric = ['age','education-num','hours-per-week']
categorical = ['workclass','marital-status','occupation','native-country']

In [17]:
# Pipeline

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# 1. Tahapan Preprocessing
ct = ColumnTransformer(transformers=[
    ('num', StandardScaler(), numeric), # encoding numeric menjadi standard scaler
    ('cat', OneHotEncoder(), categorical) # encoding categorical menjadi onehotencode
])

In [18]:
from sklearn.pipeline import Pipeline

# Menyimpan proses-proses
pipeline_rfc = Pipeline([
    ('preprocessing', ct), # preprocessing
    ('model', best_rfc) # pemodelan
])

In [19]:
# pisahkan datanya sebelum di fitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [20]:
# Fitting
pipeline_rfc.fit(X_train,y_train)

d:\DEVELOPMENTS\BELAJAR\dsml\.venv\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'education-num',
                                                   'hours-per-week']),
                                                 ('cat', OneHotEncoder(),
                                                  ['workclass',
                                                   'marital-status',
                                                   'occupation',
                                                   'native-country'])])),
                ('model',
                 RandomForestClassifier(max_depth=10, min_samples_leaf=5,
                                        n_estimators=150))])

In [21]:
# Prediksi

pipeline_rfc.predict(X_test)

array(['<=50K', '<=50K', '<=50K', ..., '<=50K', '>50K', '<=50K'],
      dtype=object)

In [22]:
# menyimpan pipeline
joblib.dump(pipeline_rfc, 'pipeline_rfc_joblib')

['pipeline_rfc_joblib']

In [23]:
# Membuat function
def prediksi():
    data = {}

    for i in numeric: # inputan numeric
        data[i] = float(input(f'masukkan nilai {i}:')) # str to float

    for i in categorical: # inputan categorical
            data[i] = input(f'masukkan nilai {i}:')

    data = pd.DataFrame(data, index=[0]) # convert ke DataFrame, harus ada index
    return pipeline_rfc.predict(data)

In [24]:
# jalankan function prediksi
prediksi()

ValueError: could not convert string to float: ''

In [ ]:
pd.DataFrame({
    'nama': 'dian',
    'age': 9
}, index=[0])

   nama  age
0  dian    9

In [ ]:
# sample data prediksi
X.loc[0]

workclass             State-gov
age                          39
education-num                13
marital-status    Never-married
occupation         Adm-clerical
hours-per-week               40
native-country    United-States
Name: 0, dtype: object

## AUTOML
use pycaret

jupiter !pip install pycaret

powershell python -m pip install pycaret

In [ ]:
# Use Case Classification